//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp32Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_M_Supplier()
        {
            this.TB_M_Item = new HashSet<TB_M_Item>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTimeOffset createDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_M_Item> TB_M_Item { get; set; }
    }
}
